create table if not exists app_users (
    id bigint generated by default as identity primary key,
    full_name varchar(120) not null,
    email varchar(120) not null unique,
    password varchar(255) not null,
    role varchar(30) not null,
    active boolean not null
);

create table if not exists products (
    id bigint generated by default as identity primary key,
    sku varchar(50) not null unique,
    name varchar(120) not null,
    price numeric(15,2) not null,
    active boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists customers (
    id bigint generated by default as identity primary key,
    customer_code varchar(50) not null unique,
    full_name varchar(150) not null,
    email varchar(120) not null unique,
    phone varchar(30) not null,
    registration_date date not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists suppliers (
    id bigint generated by default as identity primary key,
    supplier_code varchar(50) not null unique,
    company_name varchar(150) not null,
    email varchar(120) not null unique,
    phone varchar(30) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists employees (
    id bigint generated by default as identity primary key,
    employee_code varchar(50) not null unique,
    full_name varchar(150) not null,
    email varchar(120) not null unique,
    phone varchar(30) not null,
    hire_date date not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists inventory_items (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    quantity integer not null,
    warehouse_location varchar(80) not null,
    last_updated date not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_inventory_product foreign key (product_id) references products(id)
);

create table if not exists import_jobs (
    id bigint generated by default as identity primary key,
    file_name varchar(180) not null,
    entity_type varchar(30) not null,
    file_type varchar(20) not null,
    import_mode varchar(30) not null,
    status varchar(30) not null,
    total_records integer not null,
    successful_records integer not null,
    failed_records integer not null,
    duration_ms bigint not null,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    initiated_by_user_id bigint not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_import_job_user foreign key (initiated_by_user_id) references app_users(id)
);

create table if not exists import_errors (
    id bigint generated by default as identity primary key,
    row_number integer not null,
    field_name varchar(120),
    rejected_value varchar(255),
    error_type varchar(40) not null,
    severity varchar(20) not null,
    message varchar(255) not null,
    import_job_id bigint not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_import_error_job foreign key (import_job_id) references import_jobs(id)
);

create index if not exists idx_import_job_created_at on import_jobs(created_at);
create index if not exists idx_import_job_status on import_jobs(status);
create index if not exists idx_import_job_entity_type on import_jobs(entity_type);
create index if not exists idx_import_error_type on import_errors(error_type);
create index if not exists idx_import_error_job on import_errors(import_job_id);
